"""feat: expand usuario profile fields

Revision ID: 0011058262f1
Revises: fa507ac7b9b7
Create Date: 2026-06-19 17:39:40.632077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011058262f1'
down_revision: Union[str, Sequence[str], None] = 'fa507ac7b9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('banco', sa.String(length=100), nullable=True))
    op.add_column('usuario', sa.Column('regional', sa.String(length=100), nullable=True))
    op.add_column('usuario', sa.Column('genero', sa.String(length=50), nullable=True))
    op.add_column('usuario', sa.Column('es_monotributista', sa.Boolean(), nullable=True))
    op.add_column('usuario', sa.Column('identificador_profesional', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'identificador_profesional')
    op.drop_column('usuario', 'es_monotributista')
    op.drop_column('usuario', 'genero')
    op.drop_column('usuario', 'regional')
    op.drop_column('usuario', 'banco')
    # ### end Alembic commands ###
