"""003_audit_log

Revision ID: 06b953a30121
Revises: cd85bc74e708
Create Date: 2026-06-07 18:35:41.969779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b953a30121'
down_revision: Union[str, Sequence[str], None] = 'cd85bc74e708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('impersonado_id', sa.UUID(), nullable=True),
    sa.Column('materia_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=255), nullable=False),
    sa.Column('detalle', sa.JSON(), nullable=True),
    sa.Column('filas_afectadas', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['usuario.id'], name=op.f('fk_audit_log_actor_id_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['impersonado_id'], ['usuario.id'], name=op.f('fk_audit_log_impersonado_id_usuario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_audit_log_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_accion'), 'audit_log', ['accion'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    
    # Trigger to prevent updates and deletes
    op.execute("""
    CREATE OR REPLACE FUNCTION prevent_update_delete_audit()
    RETURNS TRIGGER AS $$
    BEGIN
        RAISE EXCEPTION 'Updates and deletes are not allowed on the audit_log table';
        RETURN NULL;
    END;
    $$ LANGUAGE plpgsql;
    """)
    op.execute("""
    CREATE TRIGGER trg_prevent_update_delete_audit
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION prevent_update_delete_audit();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_accion'), table_name='audit_log')
    op.drop_table('audit_log')
    
    op.execute("DROP TRIGGER IF EXISTS trg_prevent_update_delete_audit ON audit_log;")
    op.execute("DROP FUNCTION IF EXISTS prevent_update_delete_audit;")
    # ### end Alembic commands ###
