"""003_recovery_token

Revision ID: 28ebbf327457
Revises: 7643f3084128
Create Date: 2026-06-07 17:56:12.972533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28ebbf327457'
down_revision: Union[str, Sequence[str], None] = '7643f3084128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recovery_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], name=op.f('fk_recovery_token_user_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_token'))
    )
    op.create_index(op.f('ix_recovery_token_token'), 'recovery_token', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_token_token'), table_name='recovery_token')
    op.drop_table('recovery_token')
    # ### end Alembic commands ###
