"""004_carrera_cohorte_materia

Revision ID: ad401134c7c7
Revises: 06b953a30121
Create Date: 2026-06-07 18:46:24.145229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad401134c7c7'
down_revision: Union[str, Sequence[str], None] = '06b953a30121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrera',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'INACTIVA', name='estadoestructura', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_carrera_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carrera')),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_carrera_tenant_codigo')
    )
    op.create_index(op.f('ix_carrera_tenant_id'), 'carrera', ['tenant_id'], unique=False)
    op.create_table('materia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'INACTIVA', name='estadoestructura', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_materia_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materia')),
    sa.UniqueConstraint('tenant_id', 'codigo', name='uq_materia_tenant_codigo')
    )
    op.create_index(op.f('ix_materia_tenant_id'), 'materia', ['tenant_id'], unique=False)
    op.create_table('cohorte',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('carrera_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('vig_desde', sa.Date(), nullable=False),
    sa.Column('vig_hasta', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'INACTIVA', name='estadoestructura', native_enum=False, length=20), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id'], name=op.f('fk_cohorte_carrera_id_carrera')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_cohorte_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cohorte')),
    sa.UniqueConstraint('tenant_id', 'carrera_id', 'nombre', name='uq_cohorte_tenant_carrera_nombre')
    )
    op.create_index(op.f('ix_cohorte_carrera_id'), 'cohorte', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_cohorte_tenant_id'), 'cohorte', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cohorte_tenant_id'), table_name='cohorte')
    op.drop_index(op.f('ix_cohorte_carrera_id'), table_name='cohorte')
    op.drop_table('cohorte')
    op.drop_index(op.f('ix_materia_tenant_id'), table_name='materia')
    op.drop_table('materia')
    op.drop_index(op.f('ix_carrera_tenant_id'), table_name='carrera')
    op.drop_table('carrera')
    # ### end Alembic commands ###
