"""Add ProgramaMateria and FechaAcademica

Revision ID: c270cd264cf9
Revises: 071c08f3e6d7
Create Date: 2026-06-08 03:05:51.542822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core.crypto
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c270cd264cf9'
down_revision: Union[str, Sequence[str], None] = '071c08f3e6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umbral_materia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=True),
    sa.Column('umbral_pct', sa.Float(), nullable=False),
    sa.Column('valores_aprobatorios', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_umbral_materia_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_umbral_materia'))
    )
    op.create_index(op.f('ix_umbral_materia_docente_id'), 'umbral_materia', ['docente_id'], unique=False)
    op.create_index(op.f('ix_umbral_materia_materia_id'), 'umbral_materia', ['materia_id'], unique=False)
    op.create_index(op.f('ix_umbral_materia_tenant_id'), 'umbral_materia', ['tenant_id'], unique=False)
    op.create_table('fecha_academica',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('materia_id', sa.Uuid(), nullable=False),
    sa.Column('cohorte_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.Enum('PARCIAL', 'RECUPERATORIO', 'TP', 'COLOQUIO', 'FINAL', 'OTRO', name='tipofechaacademica', native_enum=False, length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('es_feriado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cohorte_id'], ['cohorte.id'], name=op.f('fk_fecha_academica_cohorte_id_cohorte')),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], name=op.f('fk_fecha_academica_materia_id_materia')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_fecha_academica_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fecha_academica'))
    )
    op.create_index(op.f('ix_fecha_academica_cohorte_id'), 'fecha_academica', ['cohorte_id'], unique=False)
    op.create_index(op.f('ix_fecha_academica_materia_id'), 'fecha_academica', ['materia_id'], unique=False)
    op.create_index(op.f('ix_fecha_academica_tenant_id'), 'fecha_academica', ['tenant_id'], unique=False)
    op.create_table('programa_materia',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('materia_id', sa.Uuid(), nullable=False),
    sa.Column('carrera_id', sa.Uuid(), nullable=True),
    sa.Column('cohorte_id', sa.Uuid(), nullable=True),
    sa.Column('referencia_archivo', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id'], name=op.f('fk_programa_materia_carrera_id_carrera')),
    sa.ForeignKeyConstraint(['cohorte_id'], ['cohorte.id'], name=op.f('fk_programa_materia_cohorte_id_cohorte')),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], name=op.f('fk_programa_materia_materia_id_materia')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_programa_materia_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programa_materia'))
    )
    op.create_index(op.f('ix_programa_materia_carrera_id'), 'programa_materia', ['carrera_id'], unique=False)
    op.create_index(op.f('ix_programa_materia_cohorte_id'), 'programa_materia', ['cohorte_id'], unique=False)
    op.create_index(op.f('ix_programa_materia_materia_id'), 'programa_materia', ['materia_id'], unique=False)
    op.create_index(op.f('ix_programa_materia_tenant_id'), 'programa_materia', ['tenant_id'], unique=False)
    op.create_table('version_padron',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.Uuid(), nullable=False),
    sa.Column('cohorte_id', sa.Uuid(), nullable=False),
    sa.Column('cargado_por', sa.UUID(), nullable=False),
    sa.Column('cargado_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cargado_por'], ['usuario.id'], name=op.f('fk_version_padron_cargado_por_usuario'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cohorte_id'], ['cohorte.id'], name=op.f('fk_version_padron_cohorte_id_cohorte'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], name=op.f('fk_version_padron_materia_id_materia'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_version_padron_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_version_padron'))
    )
    op.create_index(op.f('ix_version_padron_cohorte_id'), 'version_padron', ['cohorte_id'], unique=False)
    op.create_index(op.f('ix_version_padron_materia_id'), 'version_padron', ['materia_id'], unique=False)
    op.create_index(op.f('ix_version_padron_tenant_id'), 'version_padron', ['tenant_id'], unique=False)
    op.create_table('entrada_padron',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellidos', sa.String(length=255), nullable=False),
    sa.Column('email', core.crypto.EncryptedString(), nullable=False),
    sa.Column('comision', sa.String(length=100), nullable=True),
    sa.Column('regional', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_entrada_padron_tenant_id_tenant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_entrada_padron_usuario_id_usuario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['version_padron.id'], name=op.f('fk_entrada_padron_version_id_version_padron'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entrada_padron'))
    )
    op.create_index(op.f('ix_entrada_padron_tenant_id'), 'entrada_padron', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_entrada_padron_usuario_id'), 'entrada_padron', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_entrada_padron_version_id'), 'entrada_padron', ['version_id'], unique=False)
    op.create_table('calificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entrada_padron_id', sa.UUID(), nullable=False),
    sa.Column('actividad_nombre', sa.String(length=255), nullable=False),
    sa.Column('nota_numerica', sa.Float(), nullable=True),
    sa.Column('nota_textual', sa.String(length=255), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entrada_padron_id'], ['entrada_padron.id'], name=op.f('fk_calificacion_entrada_padron_id_entrada_padron')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_calificacion_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calificacion'))
    )
    op.create_index(op.f('ix_calificacion_entrada_padron_id'), 'calificacion', ['entrada_padron_id'], unique=False)
    op.create_index(op.f('ix_calificacion_tenant_id'), 'calificacion', ['tenant_id'], unique=False)
    op.drop_column('facturas', 'created_at')
    op.drop_column('facturas', 'deleted_at')
    op.drop_column('facturas', 'updated_at')
    op.alter_column('guardias', 'dia',
               existing_type=postgresql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='diasemana_guardia'),
               type_=sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='diasemana'),
               existing_nullable=False,
               postgresql_using="dia::text::diasemana")
    op.alter_column('instancias_encuentros', 'slot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_instancias_encuentros_slot_id'), table_name='instancias_encuentros')
    op.drop_column('liquidaciones', 'created_at')
    op.drop_column('liquidaciones', 'deleted_at')
    op.drop_column('liquidaciones', 'updated_at')
    op.drop_column('salarios_base', 'created_at')
    op.drop_column('salarios_base', 'deleted_at')
    op.drop_column('salarios_base', 'updated_at')
    op.drop_column('salarios_plus', 'created_at')
    op.drop_column('salarios_plus', 'deleted_at')
    op.drop_column('salarios_plus', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salarios_plus', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('salarios_plus', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('salarios_plus', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('salarios_base', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('salarios_base', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('salarios_base', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('liquidaciones', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('liquidaciones', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('liquidaciones', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_instancias_encuentros_slot_id'), 'instancias_encuentros', ['slot_id'], unique=False)
    op.alter_column('instancias_encuentros', 'slot_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('guardias', 'dia',
               existing_type=sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='diasemana'),
               type_=postgresql.ENUM('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='diasemana_guardia'),
               existing_nullable=False)
    op.add_column('facturas', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('facturas', sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('facturas', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_calificacion_tenant_id'), table_name='calificacion')
    op.drop_index(op.f('ix_calificacion_entrada_padron_id'), table_name='calificacion')
    op.drop_table('calificacion')
    op.drop_index(op.f('ix_entrada_padron_version_id'), table_name='entrada_padron')
    op.drop_index(op.f('ix_entrada_padron_usuario_id'), table_name='entrada_padron')
    op.drop_index(op.f('ix_entrada_padron_tenant_id'), table_name='entrada_padron')
    op.drop_table('entrada_padron')
    op.drop_index(op.f('ix_version_padron_tenant_id'), table_name='version_padron')
    op.drop_index(op.f('ix_version_padron_materia_id'), table_name='version_padron')
    op.drop_index(op.f('ix_version_padron_cohorte_id'), table_name='version_padron')
    op.drop_table('version_padron')
    op.drop_index(op.f('ix_programa_materia_tenant_id'), table_name='programa_materia')
    op.drop_index(op.f('ix_programa_materia_materia_id'), table_name='programa_materia')
    op.drop_index(op.f('ix_programa_materia_cohorte_id'), table_name='programa_materia')
    op.drop_index(op.f('ix_programa_materia_carrera_id'), table_name='programa_materia')
    op.drop_table('programa_materia')
    op.drop_index(op.f('ix_fecha_academica_tenant_id'), table_name='fecha_academica')
    op.drop_index(op.f('ix_fecha_academica_materia_id'), table_name='fecha_academica')
    op.drop_index(op.f('ix_fecha_academica_cohorte_id'), table_name='fecha_academica')
    op.drop_table('fecha_academica')
    op.drop_index(op.f('ix_umbral_materia_tenant_id'), table_name='umbral_materia')
    op.drop_index(op.f('ix_umbral_materia_materia_id'), table_name='umbral_materia')
    op.drop_index(op.f('ix_umbral_materia_docente_id'), table_name='umbral_materia')
    op.drop_table('umbral_materia')
    # ### end Alembic commands ###
