"""comunicaciones

Revision ID: comunicaciones_12
Revises: 
Create Date: 2026-06-07 23:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'comunicaciones_12'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comunicaciones',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('lote_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('destinatario_cifrado', sa.String(), nullable=False),
    sa.Column('asunto', sa.String(length=255), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENVIANDO', 'ENVIADO', 'ERROR', 'CANCELADO', name='estadocomunicacion'), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.CheckConstraint("estado != 'Error' OR error_msg IS NOT NULL", name='chk_error_msg_if_error'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comunicaciones_estado'), 'comunicaciones', ['estado'], unique=False)
    op.create_index(op.f('ix_comunicaciones_aprobado'), 'comunicaciones', ['aprobado'], unique=False)
    op.create_index(op.f('ix_comunicaciones_id'), 'comunicaciones', ['id'], unique=False)
    op.create_index(op.f('ix_comunicaciones_lote_id'), 'comunicaciones', ['lote_id'], unique=False)
    op.create_index(op.f('ix_comunicaciones_tenant_id'), 'comunicaciones', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comunicaciones_tenant_id'), table_name='comunicaciones')
    op.drop_index(op.f('ix_comunicaciones_lote_id'), table_name='comunicaciones')
    op.drop_index(op.f('ix_comunicaciones_id'), table_name='comunicaciones')
    op.drop_index(op.f('ix_comunicaciones_estado'), table_name='comunicaciones')
    op.drop_index(op.f('ix_comunicaciones_aprobado'), table_name='comunicaciones')
    op.drop_table('comunicaciones')
    # ### end Alembic commands ###
