"""c07 usuario asignacion

Revision ID: e483d139959a
Revises: ad401134c7c7
Create Date: 2026-06-07 19:07:46.512670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core

# revision identifiers, used by Alembic.
revision: str = 'e483d139959a'
down_revision: Union[str, Sequence[str], None] = 'ad401134c7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('rol_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=True),
    sa.Column('carrera_id', sa.UUID(), nullable=True),
    sa.Column('cohorte_id', sa.UUID(), nullable=True),
    sa.Column('responsable_id', sa.UUID(), nullable=True),
    sa.Column('desde', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hasta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['carrera_id'], ['carrera.id'], name=op.f('fk_asignacion_carrera_id_carrera'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cohorte_id'], ['cohorte.id'], name=op.f('fk_asignacion_cohorte_id_cohorte'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materia.id'], name=op.f('fk_asignacion_materia_id_materia'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsable_id'], ['usuario.id'], name=op.f('fk_asignacion_responsable_id_usuario'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id'], name=op.f('fk_asignacion_rol_id_rol'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_asignacion_tenant_id_tenant'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_asignacion_usuario_id_usuario'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asignacion'))
    )
    op.create_index(op.f('ix_asignacion_tenant_id'), 'asignacion', ['tenant_id'], unique=False)
    op.add_column('usuario', sa.Column('email_hash', sa.String(), nullable=False))
    op.add_column('usuario', sa.Column('nombre', sa.String(), nullable=False))
    op.add_column('usuario', sa.Column('apellido', sa.String(), nullable=False))
    op.add_column('usuario', sa.Column('dni', core.crypto.EncryptedString(), nullable=True))
    op.add_column('usuario', sa.Column('cuil', core.crypto.EncryptedString(), nullable=True))
    op.add_column('usuario', sa.Column('cbu', core.crypto.EncryptedString(), nullable=True))
    op.add_column('usuario', sa.Column('alias_cbu', core.crypto.EncryptedString(), nullable=True))
    op.add_column('usuario', sa.Column('legajo', sa.String(), nullable=True))
    op.add_column('usuario', sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.create_index(op.f('ix_usuario_email_hash'), 'usuario', ['email_hash'], unique=False)
    op.create_unique_constraint('uq_usuario_tenant_email', 'usuario', ['tenant_id', 'email_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_usuario_tenant_email', 'usuario', type_='unique')
    op.drop_index(op.f('ix_usuario_email_hash'), table_name='usuario')
    op.drop_column('usuario', 'activo')
    op.drop_column('usuario', 'legajo')
    op.drop_column('usuario', 'alias_cbu')
    op.drop_column('usuario', 'cbu')
    op.drop_column('usuario', 'cuil')
    op.drop_column('usuario', 'dni')
    op.drop_column('usuario', 'apellido')
    op.drop_column('usuario', 'nombre')
    op.drop_column('usuario', 'email_hash')
    op.drop_index(op.f('ix_asignacion_tenant_id'), table_name='asignacion')
    op.drop_table('asignacion')
    # ### end Alembic commands ###
