"""add estado to factura

Revision ID: fa507ac7b9b7
Revises: avisos_dirigidos_usuario
Create Date: 2026-06-18 00:32:25.491522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa507ac7b9b7'
down_revision: Union[str, Sequence[str], None] = 'avisos_dirigidos_usuario'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_candidato_coloquio_tenant_id_tenant'), 'candidato_coloquio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_candidato_coloquio_tenant_id_tenant'), 'candidato_coloquio', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('fk_convocatoria_coloquio_tenant_id_tenant'), 'convocatoria_coloquio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_convocatoria_coloquio_tenant_id_tenant'), 'convocatoria_coloquio', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    estado_enum = sa.Enum('PENDIENTE', 'ABONADA', name='estado_factura_enum')
    estado_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('facturas', sa.Column('estado', estado_enum, nullable=False, server_default='PENDIENTE'))
    op.add_column('facturas', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('facturas', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('facturas', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('liquidaciones', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('liquidaciones', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('liquidaciones', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('fk_reserva_coloquio_tenant_id_tenant'), 'reserva_coloquio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reserva_coloquio_tenant_id_tenant'), 'reserva_coloquio', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('salarios_base', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('salarios_base', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('salarios_base', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('salarios_plus', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('salarios_plus', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('salarios_plus', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('fk_turno_coloquio_tenant_id_tenant'), 'turno_coloquio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_turno_coloquio_tenant_id_tenant'), 'turno_coloquio', 'tenant', ['tenant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_turno_coloquio_tenant_id_tenant'), 'turno_coloquio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_turno_coloquio_tenant_id_tenant'), 'turno_coloquio', 'tenant', ['tenant_id'], ['id'])
    op.drop_column('salarios_plus', 'deleted_at')
    op.drop_column('salarios_plus', 'updated_at')
    op.drop_column('salarios_plus', 'created_at')
    op.drop_column('salarios_base', 'deleted_at')
    op.drop_column('salarios_base', 'updated_at')
    op.drop_column('salarios_base', 'created_at')
    op.drop_constraint(op.f('fk_reserva_coloquio_tenant_id_tenant'), 'reserva_coloquio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_reserva_coloquio_tenant_id_tenant'), 'reserva_coloquio', 'tenant', ['tenant_id'], ['id'])
    op.drop_column('liquidaciones', 'deleted_at')
    op.drop_column('liquidaciones', 'updated_at')
    op.drop_column('liquidaciones', 'created_at')
    op.drop_column('facturas', 'deleted_at')
    op.drop_column('facturas', 'updated_at')
    op.drop_column('facturas', 'created_at')
    op.drop_column('facturas', 'estado')
    op.drop_constraint(op.f('fk_convocatoria_coloquio_tenant_id_tenant'), 'convocatoria_coloquio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_convocatoria_coloquio_tenant_id_tenant'), 'convocatoria_coloquio', 'tenant', ['tenant_id'], ['id'])
    op.drop_constraint(op.f('fk_candidato_coloquio_tenant_id_tenant'), 'candidato_coloquio', type_='foreignkey')
    op.create_foreign_key(op.f('fk_candidato_coloquio_tenant_id_tenant'), 'candidato_coloquio', 'tenant', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
